GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJzb3NhMyIsImlkIjoiNjc4NjlhYWVkMzEyMGZhYWU4NDhjZjRmIiwiaWF0IjoxNzM2ODc0OTEzLCJleHAiOjE3MzY4Nzg1MTN9.i-2Mc7ihC5Lh2EnaAPbiaUw1jb9uXcL10UaHVB5X_d8